version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/testProject
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache
      - ./:/var/www/testProject
    restart: always
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
